version: '3'

services:
  polls-service:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: polls
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
