# Generated by Django 3.0.6 on 2020-05-29 19:51
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("polls", "0002_auto_20200528_0614")]

    operations = [migrations.RenameModel(old_name="Votes", new_name="Vote")]
