# Generated by Django 3.0.6 on 2020-05-27 20:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("polls", "0002_auto_20200527_1959")]

    operations = [
        migrations.AddField(
            model_name="userchoice",
            name="question",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="polls.Question"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(name="userchoice", unique_together={("question", "user")}),
    ]
