# Generated by Django 3.0.6 on 2020-05-27 20:59
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("polls", "0003_auto_20200527_2053")]

    operations = [migrations.RenameModel(old_name="UserChoice", new_name="Votes")]
